name: Test to build Docker image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.ruby_version }}-${{ matrix.freebsd_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        freebsd_version:
          - "15.0"
          - "14.2"
        ruby_version:
          - 3.1.6
          - 3.2.4
          - 3.3.3

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          rake docker:build arch=amd64 ruby_version=${{ matrix.ruby_version }} freebsd_version=${{ matrix.freebsd_version }}

      - name: Check image
        run: |
          docker images
          docker run ghcr.io/labtec/ruby:${{ matrix.ruby_version }}-${{ matrix.freebsd_version }} ruby -v
